[package]
name = "blockary"
version = "0.1.0"
edition = "2024"

[dependencies]
pulldown-cmark = "0.13.0"
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.10"
walkdir = "2.5.0"
